services:
  frontend-service:
    container_name: frontend-service
    image: nicohrubec/doc-rag-frontend-service
    build:
      dockerfile: Dockerfile
      context: ./frontend
    command: python3 -m flask run --host=0.0.0.0 --port=9000
    environment:
      - PORT=9000
      - DOCKER_NETWORK=true
    volumes:
      - ./frontend:/app
    ports:
      - 9000:9000
  backend-service:
    container_name: backend-service
    image: nicohrubec/doc-rag-backend-service
    build:
      dockerfile: Dockerfile
      context: ./api
    command: python3 -m flask run --host=0.0.0.0 --port=8000
    environment:
      - PORT=8000
    env_file:
      - .env
    volumes:
      - ./api:/app
    ports:
      - 8000:8000
